name: Deploy Lambda A

on:
  push:
    branches: [main]
    paths:
      - 'lambda-function-a/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Package Lambda A
        run: |
          mkdir -p build/a
          cp lambda-function-a/index.js build/a/
          cp package.json build/a/
          cp -r node_modules build/a/
          cd build/a && zip -r ../function-a.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Lambda A
        run: |
          aws lambda update-function-code \
            --function-name lambda-function-a \
            --zip-file fileb://build/function-a.zip
